seed: 0

env:
  name: open

model:
  architecture: eqnet
  skips: false

paths:
  work_dir: runs

dataset:
  type: flat
  args:
    horizon: 32

train:
  args:
    timesteps: 200
    lr: 1e-4
    batch_size: 128
    guidance_scale: 2.0
    hidden_dim: 128
    time_dim: 32
    n_layers: 10
    epochs: 20
    save_every: 5
