  
env: "medium"

paths: 
  work_dir: runs
  task_file: /scratch/network/ts4953/recloned/rpmml-project/timeskip-diffuser/src/timeskip_diffuser/datasets/point_maze/start_goal/medium_start_goal_100.npz
  ckpt_file: /scratch/network/ts4953/recloned/rpmml-project/timeskip-diffuser/src/timeskip_diffuser/pipelines/trained/medium_unet_flat_seed0_20251222_014732/checkpoints/diffuser_unet_epoch_20.pt
  dataset_file: /scratch/network/ts4953/recloned/rpmml-project/timeskip-diffuser/src/timeskip_diffuser/datasets/offline_datasets/medium_h32_mu1_sig1.npz

model:
  architecture: unet
  skips: false

testing:
  horizon: 64
  max_tries: 1
  allowed_eps: 0.2 #within start and goal
  max_allowed_jump: 0.2
